name: awarely
description: "Awarely - The Context-Aware Reminder Assistant. Never forget what matters."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  
  # Local Storage
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  
  # Context Detection
  geolocator: ^10.1.0
  geofence_service: ^6.0.0+1
  connectivity_plus: ^5.0.2
  permission_handler: ^11.1.0
  
  # Background Tasks
  workmanager: ^0.6.0
  
  # Notifications
  # Use the latest available compatible version
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  
  # Firebase (for future cloud sync)
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  collection: ^1.18.0
  
  # Speech & NLU
  speech_to_text: ^7.0.0
  http: ^1.2.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env
